inherit_from:
  - https://dev.k.io/rubocop/rubocop.rails.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
