web:
  host: postal.example.com
  protocol: https

web_server:
  bind_address: 0.0.0.0
  port: 5000
  max_threads: 5

fast_server:
  bind_address: 0.0.0.0
  port: 5010
  ssl_port: 5011
  proxy_protocol: false

general:
  use_ip_pools: false
  exception_url: null

logging:
  stdout: false
  max_log_file_size: 20
  max_log_files: 10

main_db:
  host: localhost
  port: 3306
  username: root
  password:
  database: postal

message_db:
  host: localhost
  port: 3306
  username: root
  password:
  prefix: postal

rabbitmq:
  host: localhost
  port: 5672
  username: postal
  password: xxx
  vhost: /postal

smtp_server:
  proxy_protocol: false
  log_connect: true
  evented: true
  ports:
    - 2525

dns:
  mx_records:
    - mx1.example.com
    - mx2.example.com
  smtp_server_hostname: smtp.example.com
  spf_include: spf.example.com
  return_path: rp.example.com
  route_domain: routes.example.com
  track_domain: track.example.com
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp:
  host: smtp.blah
  port: 2525
  username:
  password:
  from_name: Postal
  from_address: postal@yourdomain.com

espect:
  hosts:
    - http://espect01.infra.atech.io

rails:
  environment: production
  secret_key: {{secretkey}}

